In [ ]:
Consider the below code to answer further questions:


import numpy as np

list_ = [ ‘1’ , ’2’ , ‘3’ , ‘4’ , ‘5’ ]

array_list = np.array(object = list_)


Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code 
to print the data types of both the variables.

In [3]:
import numpy as np
list_ = ["1","2","3","4","5"]
array_list = np.array(object=list_)

In [4]:
array_list

array(['1', '2', '3', '4', '5'], dtype='<U1')

In [ ]:
yes there is a difference because list_ variable has a list type of data and array_list contain data in array form which means 
it is an n dimension array

In [5]:
print(type(list_))
print(type(array_list))

<class 'list'>
<class 'numpy.ndarray'>


In [ ]:
Q2. Write a code to print the data type of each and every element of both the variables list_ and arra_list.

In [7]:
print(type(list_))
for i in list_:
    print(type(i))

<class 'list'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>


In [9]:
print(type(array_list))

<class 'numpy.ndarray'>


In [10]:
for i in array_list:
    print(type(i))

<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


In [ ]:
Q3. Considering the following changes in the variable, array_list:

array_list = np.array(object = list_, dtype = int)

Will there be any difference in the data type of the elements present in both the variables, list_ and arra_list? 
If so then print the data types of each and every element present in both the variables, list_ and arra_list.

In [12]:
array_list = np.array(object = list_, dtype = int)

In [13]:
array_list

array([1, 2, 3, 4, 5])

In [ ]:
yes there will be difference because list_ contain str data type object and in array_list we pass dtype is int so it contain 
int data 

In [14]:
print(type(list_))
for i in list_:
    print(type(i))

print(type(array_list))
for i in array_list :
    print(type(i))

#      all the data type of array_list are int

<class 'list'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'numpy.ndarray'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>


In [ ]:
Consider the below code to answer further questions:

import numpy as np

num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]

num_array = np.array(object = num_list)


Q4. Write a code to find the following characteristics of variable, num_array:
(i)  shape

(ii) size

In [15]:
import numpy as np
num_list = [[1,2,3],[4,5,6]]
num_array = np.array(object = num_list)

In [25]:
shape = num_array.shape
shape

(2, 3)

In [26]:
size = num_array.size
size

6

In [ ]:
Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array 
creation function.

In [32]:
z = np.zeros((3,3), dtype=int)
z

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [30]:
z = np.fromfunction(lambda i,j : i*j*0 , (3,3) ,dtype=int)

In [31]:
z

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [ ]:
Q6. Create an identity matrix of shape (5,5) using numpy functions?

In [33]:
i = np.eye(5)

In [34]:
i

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [36]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [38]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])